#!/usr/bin/env python3

import argparse
import re
import sys
from transformers import AutoTokenizer

# A regex to find all quoted literals in a GBNF file, handling escaped quotes.
LITERAL_REGEX = re.compile(r'"([^"\\\n]*(?:\\.[^"\\\n]*)*)"')

def find_unique_literals(gbnf_content):
    """Extracts all unique literal strings from GBNF content."""
    # Strip comment lines before matching
    lines = [line for line in gbnf_content.splitlines() if not line.strip().startswith('#')]
    cleaned = '\n'.join(lines)
    return set(LITERAL_REGEX.findall(cleaned))

def generate_header_content(tokenized_literals):
    """Generates the C++ header content from the tokenized data."""
    header = [
        "#pragma once",
        "",
        "// This file is auto-generated by tokenize_dsl.py. DO NOT EDIT.",
        "",
        "#include <cstdint>",
        "#include <map>",
        "#include <string>",
        "#include <vector>",
        "",
        "static const std::map<std::string, std::vector<int32_t>> pretokenized_literals = {",
    ]

    for literal, token_ids in sorted(tokenized_literals.items()):
        # Format the literal for C++ string initialization, escaping necessary characters.
        cpp_literal = literal.replace('\\', '\\\\').replace('"', '\\"')
        
        # Format the vector of token IDs.
        token_ids_str = ", ".join(map(str, token_ids))
        
        header.append(f'    {{"{cpp_literal}", {{{token_ids_str}}}}},')

    header.append("};")
    return "\n".join(header)

def encode_literal(tokenizer, literal):
    """Encode a literal fragment, preserving leading whitespace correctly."""
    if not literal:
        return []
    SENTINEL = "\x00"
    sentinel_ids = tokenizer.encode(SENTINEL, add_special_tokens=False)
    combined_ids = tokenizer.encode(SENTINEL + literal, add_special_tokens=False)
    if combined_ids[:len(sentinel_ids)] == sentinel_ids:
        return combined_ids[len(sentinel_ids):]
    return combined_ids

def main():
    """Main function to run the script."""
    parser = argparse.ArgumentParser(
        description="Parse a GBNF file to generate a C++ header with pre-tokenized literals."
    )
    parser.add_argument(
        "input_gbnf",
        type=str,
        help="Path to the input GBNF file."
    )
    parser.add_argument(
        "output_header",
        type=str,
        help="Path for the generated C++ header file."
    )
    parser.add_argument(
        "--model",
        type=str,
        default="Qwen/Qwen2-7B",
        help="HuggingFace model name for tokenizer (default: Qwen/Qwen2-7B)"
    )
    args = parser.parse_args()

    try:
        with open(args.input_gbnf, "r", encoding="utf-8") as f:
            gbnf_content = f.read()
    except FileNotFoundError:
        print(f"Error: Input file not found at {args.input_gbnf}", file=sys.stderr)
        sys.exit(1)

    literals = find_unique_literals(gbnf_content)
    
    # Using the specified tokenizer
    print(f"Loading tokenizer: {args.model}")
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    
    tokenized_literals = {}
    
    for literal in literals:
        # Original literal (no leading space)
        token_ids = encode_literal(tokenizer, literal);
        tokenized_literals[literal] = token_ids
        
        # Space-prefixed variant for literals that:
        # 1. Don't already start with whitespace
        # 2. Start with an alphanumeric character (likely to appear after space in code)
        # 3. Are not single punctuation characters
        if (literal and 
            not literal[0].isspace() and 
            (literal[0].isalnum() or literal[0] == '_') and
            len(literal) > 1):
            
            space_literal = " " + literal
            space_token_ids = encode_literal(tokenizer, literal)
            
            # Only add if the tokenization is different
            # (the space-prefixed version produces different token IDs)
            if space_token_ids != token_ids:
                tokenized_literals[space_literal] = space_token_ids
                
        # Also handle newline-prefixed variants for keywords that might appear
        # at the start of a line (like 'const', 'for', 'if', etc.)
        if (literal and 
            not literal[0].isspace() and 
            literal[0].isalpha() and
            len(literal) > 1 and
            literal.isidentifier()):
            
            newline_literal = "\n" + literal
            newline_token_ids = encode_literal(tokenizer, literal)
            
            # Only add if different from both original and space-prefixed
            if (newline_token_ids != token_ids and 
                newline_literal not in tokenized_literals):
                tokenized_literals[newline_literal] = newline_token_ids

    header_content = generate_header_content(tokenized_literals)

    with open(args.output_header, "w", encoding="utf-8") as f:
        f.write(header_content)

    # Print summary
    original_count = len(literals)
    total_count = len(tokenized_literals)
    print(f"Original literals: {original_count}")
    print(f"Total entries (with space/newline variants): {total_count}")
    print(f"Successfully generated {args.output_header} from {args.input_gbnf}")

if __name__ == "__main__":
    main()